# Generated by Django 4.2.13 on 2025-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('region', models.CharField(blank=True, choices=[('dar_es_salaam', 'Dar es Salaam'), ('arusha', 'Arusha'), ('mwanza', 'Mwanza'), ('dodoma', 'Dodoma'), ('tanga', 'Tanga'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('zanzibar', 'Zanzibar')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
