# Generated by Django 4.2.14 on 2025-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_delete_orderassignmentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/profile_images/'),
        ),
    ]
