# Generated by Django 4.2.14 on 2025-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gas', 'Gas'), ('food', 'Food'), ('groceries', 'Groceries'), ('packages', 'Packages'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('pcs', 'Pieces'), ('pkg', 'Package')], default='pcs', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='gas_type',
            field=models.CharField(blank=True, choices=[('lpg', 'LPG'), ('natural', 'Natural Gas'), ('propane', 'Propane'), ('butane', 'Butane')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tank_size',
            field=models.IntegerField(blank=True, choices=[(6, '6 KG'), (13, '13 KG'), (15, '15 KG'), (38, '38 KG'), (45, '45 KG')], null=True),
        ),
    ]
