# Generated by Django 4.2.14 on 2025-03-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_category_alter_order_business_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
