# Generated by Django 4.2.14 on 2025-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_is_active_business_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner image displayed on the business page', null=True, upload_to='business/banners/'),
        ),
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='business/covers/'),
        ),
    ]
