# Generated by Django 4.2.14 on 2025-06-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_banner_business_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('general', 'General'), ('electronics', 'Electronics'), ('food', 'Food'), ('gas', 'Gas'), ('clothing', 'Clothing'), ('furniture', 'Furniture'), ('health', 'Health & Beauty'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='is_top_level',
            field=models.BooleanField(default=False, help_text='Whether this is a main category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='business.category'),
        ),
    ]
