# Generated by Django 5.2 on 2025-06-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_category_category_type_category_is_top_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='business.business'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('business', 'slug')},
        ),
    ]
