# Generated by Django 4.2.13 on 2025-03-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, choices=[('dar_es_salaam', 'Dar es Salaam'), ('arusha', 'Arusha'), ('mwanza', 'Mwanza'), ('dodoma', 'Dodoma'), ('tanga', 'Tanga'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('zanzibar', 'Zanzibar')], max_length=50, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('consecutive_declines', models.IntegerField(blank=True, default=0, null=True)),
                ('last_decline_time', models.DateTimeField(blank=True, null=True)),
                ('block_until', models.DateTimeField(blank=True, null=True)),
                ('penalties', models.IntegerField(blank=True, default=0, help_text='Number of penalties for missing orders', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kijiwe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.kijiwe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiderPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('late_delivery', 'Late Delivery'), ('order_decline', 'Order Decline'), ('order_cancel', 'Order Cancellation'), ('complaint', 'Customer Complaint'), ('other', 'Other')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved', models.BooleanField(blank=True, default=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_records', to='riders.rider')),
            ],
            options={
                'verbose_name_plural': 'Rider Penalties',
                'ordering': ['-created_at'],
            },
        ),
    ]
