# Generated by Django 4.2.14 on 2025-03-10 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_remove_order_rider_alter_order_order_number_and_more'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riderpenalty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rider Penalty', 'verbose_name_plural': 'Rider Penalties'},
        ),
        migrations.RemoveField(
            model_name='riderpenalty',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='riderpenalty',
            name='resolution_note',
        ),
        migrations.RemoveField(
            model_name='riderpenalty',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='riderpenalty',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='riderpenalty',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='riderpenalty',
            name='type',
        ),
        migrations.AddField(
            model_name='riderpenalty',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderpenalty',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_penalties', to='orders.order'),
        ),
        migrations.AddField(
            model_name='riderpenalty',
            name='penalty_type',
            field=models.CharField(choices=[('MISSED_ORDER', 'Missed Order'), ('LATE_PICKUP', 'Late Pickup'), ('LATE_DELIVERY', 'Late Delivery'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='riderpenalty',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='riderpenalty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='riderpenalty',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_records', to='riders.rider'),
        ),
        migrations.CreateModel(
            name='RiderPenaltyOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('late_delivery', 'Late Delivery'), ('order_decline', 'Order Decline'), ('order_cancel', 'Order Cancellation'), ('complaint', 'Customer Complaint'), ('other', 'Other')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('resolved', models.BooleanField(blank=True, default=False, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_records_old', to='riders.rider')),
            ],
            options={
                'verbose_name_plural': 'Rider Penalties',
                'ordering': ['-created_at'],
            },
        ),
    ]
