# Generated by Django 4.2.14 on 2025-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_alter_riderpenalty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='id_photo',
            field=models.ImageField(blank=True, help_text="National ID or Voter's card", null=True, upload_to='riders/id_photos/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='insurance_certificate',
            field=models.ImageField(blank=True, help_text='Vehicle insurance certificate', null=True, upload_to='riders/insurance/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='latra_certificate',
            field=models.ImageField(blank=True, help_text='Land Transport Regulatory Authority certificate', null=True, upload_to='riders/latra/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='license_photo',
            field=models.ImageField(blank=True, help_text="Driver's license photo", null=True, upload_to='riders/licenses/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_photo',
            field=models.ImageField(blank=True, help_text='Photo of the delivery vehicle', null=True, upload_to='riders/vehicles/'),
        ),
    ]
