# Generated by Django 4.2.13 on 2025-04-16 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riders', '0003_rider_id_photo_rider_insurance_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('otp_timestamp', models.DateTimeField(auto_now=True)),
                ('otp_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider OTP',
                'verbose_name_plural': 'Rider OTPs',
            },
        ),
    ]
