# Generated by Django 4.2.14 on 2025-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_riderotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('boda', 'Boda'), ('guta', 'Guta'), ('kirikuu', 'Kirikuu'), ('kenta', 'Kenta')], help_text='Type of transport vehicle used by the rider', max_length=10, null=True),
        ),
    ]
