# Generated by Django 4.2.14 on 2025-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0005_rider_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo of the rider', null=True, upload_to='riders/profile_images/'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('boda', 'Boda'), ('guta', 'Guta'), ('kirikuu', 'Kirikuu'), ('kenta', 'Kenta')], default='boda', help_text='Type of transport vehicle used by the rider', max_length=10, null=True),
        ),
    ]
