# Generated by Django 4.2.14 on 2025-06-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0007_rider_address_rider_last_location_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='service_type',
            field=models.CharField(choices=[('delivery', 'Delivery Service'), ('moving_truck', 'Moving Truck'), ('water_bowser', 'Water Bowser'), ('sewage_truck', 'Sewage Truck'), ('ambulance', 'Ambulance'), ('fuel_truck', 'Fuel Truck'), ('other', 'Other')], default='delivery', help_text='Type of service provided by the rider', max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('boda', 'Boda'), ('guta', 'Guta'), ('kirikuu', 'Kirikuu'), ('kenta', 'Kenta')], default='boda', help_text='Type of transport vehicle used by the rider (for delivery service only)', max_length=10, null=True),
        ),
    ]
