# Generated by Django 5.2.2 on 2025-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0008_rider_service_type_alter_rider_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('boda', 'Boda'), ('guta', 'Guta'), ('kirikuu', 'Kirikuu'), ('kenta', 'Kenta'), ('small_truck', 'Small Truck (1-2 tons)'), ('medium_truck', 'Medium Truck (3-5 tons)'), ('large_truck', 'Large Truck (5+ tons)'), ('water_bowser', 'Water Bowser'), ('sewage_truck', 'Sewage Truck'), ('ambulance', 'Ambulance'), ('fuel_truck', 'Fuel Truck'), ('other', 'Other')], default='boda', help_text='Type of transport vehicle used by the rider (for delivery service only)', max_length=15, null=True),
        ),
    ]
