# Generated by Django 4.2.14 on 2025-03-03 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('operations', '0004_add_kijiwe_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
                ('otp_timestamp', models.DateTimeField(blank=True, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_credits', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Credit',
                'verbose_name_plural': 'OTP Credits',
                'unique_together': {('user', 'business')},
            },
        ),
    ]
