# Generated by Django 4.2.14 on 2025-03-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_otpcredit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otpcredit',
            unique_together={('user',)},
        ),
        migrations.RemoveField(
            model_name='otpcredit',
            name='business',
        ),
    ]
