# Generated by Django 4.2.14 on 2025-03-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_otpcredit_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignmentgroup',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderassignmentgroup',
            name='riders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderAssignmentGroup',
        ),
    ]
