# Generated by Django 4.2.14 on 2025-03-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_orderassignmentgroup_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('business_owner', 'Business Owner'), ('rider', 'Rider'), ('operations', 'Operations')], default='customer', max_length=15),
        ),
    ]
