# Generated by Django 4.2.14 on 2025-03-04 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uuid_tracking', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In-Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('surge_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulk_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.business')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riders.rider')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='orders.order')),
                ('riders', models.ManyToManyField(blank=True, related_name='assignment_groups', to='riders.rider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
