# Generated by Django 4.2.14 on 2025-03-08 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_location_alter_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassignmentgroup',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
