# Generated by Django 4.2.14 on 2025-03-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_banner_business_cover_image'),
        ('orders', '0006_order_pickup_latitude_order_pickup_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_orders', to='business.business'),
        ),
    ]
