# Generated by Django 4.2.14 on 2025-03-13 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_alter_riderpenalty_options_and_more'),
        ('orders', '0008_remove_order_rider_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRiderAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('assigned', 'Assigned'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('started', 'Started Delivery'), ('arrived_pickup', 'Arrived at Pickup'), ('collected', 'Collected Gas Tanks'), ('in_transit', 'In Transit'), ('arrived_delivery', 'Arrived at Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_actions', to='orders.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_actions', to='riders.rider')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order', 'rider', 'action_type'], name='orders_orde_order_i_20c6e9_idx'), models.Index(fields=['rider', 'action_type'], name='orders_orde_rider_i_3e2440_idx'), models.Index(fields=['order', 'action_type'], name='orders_orde_order_i_c76410_idx')],
            },
        ),
    ]
