# Generated by Django 4.2.14 on 2025-03-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_alter_riderpenalty_options_and_more'),
        ('orders', '0009_orderrideraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='riders.rider'),
        ),
        migrations.AlterField(
            model_name='orderrideraction',
            name='action_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('started', 'Started Delivery'), ('arrived_pickup', 'Arrived at Pickup'), ('collected', 'Collected Gas Tanks'), ('in_transit', 'In Transit'), ('arrived_delivery', 'Arrived at Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
