# Generated by Django 4.2.14 on 2025-03-18 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_alter_riderpenalty_options_and_more'),
        ('orders', '0010_order_rider_alter_orderrideraction_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderassignmentgroup',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='orderassignmentgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='riders.rider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('in_transit', 'In-Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderassignmentgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderassignmentgroup',
            name='group_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='orderassignmentgroup',
            name='riders',
            field=models.ManyToManyField(related_name='assignment_groups', to='riders.rider'),
        ),
    ]
