# Generated by Django 4.2.13 on 2025-04-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderassignmentgroup_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transport_modes/')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this transport mode', max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Additional price per kilometer', max_digits=10)),
                ('max_distance', models.IntegerField(default=50, help_text='Maximum delivery distance in kilometers')),
                ('max_weight', models.DecimalField(decimal_places=2, default=20, help_text='Maximum weight capacity in kg', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='transport_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.transportmode'),
        ),
    ]
