# Generated by Django 4.2.14 on 2025-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
